version: 0.2
phases:
  install:
    commands:
      - sudo apt-get update -y
      - sudo apt-get -y install git
      - sudo pip install --upgrade --user awscli
  build:
    commands:
      - pwd
      - ls -la
artifacts:
  files:
    - '**/*'
  discard-paths: no
